version: "2"

networks:
  bookcase-net:

services:
  database:
    hostname: database
    image: mongo
    networks:
      - bookcase-net
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/start-mongo.sh:/opt/start-mongo.sh
      - ./mongo/data:/data
    command: /opt/start-mongo.sh

  server_prod:
    hostname: server
    image: node:latest
    working_dir: /opt/app
    env_file:
      - .env-prod
    ports:
      - "4000:4000"
    networks:
      - bookcase-net
    volumes:
      - ./server:/opt/app
      - ./scripts/run-node-prod.sh:/opt/run-node-prod.sh
    command: /opt/run-node-prod.sh
